#!/bin/bash
set -euo pipefail

rm -rf build
mkdir build

cd src
zip -r ../build/paper-relations.xpi \
	bootstrap.js \
	locale \
	paper-relations-storage.js \
	paper-relations-graph-workspace.js \
	paper-relations.js \
	manifest.json \
	prefs.js \
	style.css
cd ../build

jq ".addons[\"paper-relations@example.com\"].updates[0].update_hash = \"sha256:`shasum -a 256 paper-relations.xpi | cut -d' ' -f1`\"" ../updates.json.tmpl > updates.json

