#!/bin/bash
set -euo pipefail

rm -rf build
mkdir build

cd src-2.0
zip -r ../build/paper-relations-2.0.xpi \
	bootstrap.js \
	locale \
	paper-relations.js \
	manifest.json \
	prefs.js \
	style.css
cd ../build

jq ".addons[\"paper-relations@example.com\"].updates[0].update_hash = \"sha256:`shasum -a 256 paper-relations-2.0.xpi | cut -d' ' -f1`\"" ../updates-2.0.json.tmpl > updates-2.0.json

